name: environment_microalgae_ubuntu
channels:
  - defaults
  - conda-forge
  - cmutel
  - bsteubing
  - haasad
  - pascallesage
dependencies:
  - python=3.8
  - activity-browser-dev
  - spyder=4.1.4
  - notebook
  - pulp
  - ipython
  - pyqt
  - requests
  - paramiko
  - anyjson
  - salib=1.3.11
  - scipy=1.6.0
