name: environment_microalgae_windows
channels:
  - plotly
  - defaults
  - conda-forge
  - cmutel
  - bsteubing
  - haasad
  - pascallesage
dependencies:
  - access=1.1.3
  - activity-browser-dev=2021.01.25
  - affine=2.3.0
  - alabaster=0.7.12
  - amply=0.1.4
  - anyio=2.2.0
  - anyjson=0.3.3
  - appdirs=1.4.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow=0.17.0
  - asteval=0.9.16
  - astroid=2.3.3
  - astunparse=1.6.3
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=20.3.0
  - autopep8=1.5.4
  - babel=2.9.0
  - backcall=0.2.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.10.0
  - blas=1.0
  - bleach=3.3.0
  - blosc=1.21.0
  - bokeh=2.4.2
  - boost-cpp=1.74.0
  - brightway2=2.3
  - brotlipy=0.7.0
  - bs4=4.10.0
  - bw2analyzer=0.9.4
  - bw2calc=1.8.0
  - bw2data=3.6.2
  - bw2io=0.7.12
  - bw2parameters=0.6.6
  - bw_migrations=0.1
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - cairo=1.16.0
  - cartopy=0.20.2
  - certifi=2021.10.8
  - cffi=1.14.4
  - cfitsio=4.0.0
  - chardet=4.0.0
  - click=7.1.2
  - click-plugins=1.1.1
  - cligj=0.7.2
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - contextily=1.2.0
  - coverage=5.5
  - cryptography=3.3.1
  - curl=7.80.0
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask=2021.10.0
  - dask-core=2021.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20200713
  - distributed=2021.10.0
  - docopt=0.6.2
  - docutils=0.16
  - eidl=1.2.0
  - eidl7zip=1.0.0
  - eight=1.0.0
  - entrypoints=0.3
  - esda=2.4.1
  - et_xmlfile=1.0.1
  - expat=2.4.1
  - fasteners=0.14.1
  - fiona=1.8.20
  - flake8=3.8.4
  - flask=1.1.2
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freetype=2.10.4
  - freexl=1.0.6
  - fsspec=2022.1.0
  - future=0.18.2
  - fuzzywuzzy=0.18.0
  - gdal=3.4.0
  - geographiclib=1.52
  - geopandas=0.9.0
  - geopandas-base=0.9.0
  - geoplot=0.4.4
  - geopy=2.2.0
  - geos=3.10.1
  - geotiff=1.7.0
  - gettext=0.19.8.1
  - giddy=2.3.3
  - glpk=4.65
  - hdf4=4.2.15
  - hdf5=1.12.1
  - heapdict=1.0.1
  - icc_rt=2019.0.0
  - icu=68.2
  - idna=2.10
  - imagesize=1.2.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - inequality=1.0.0
  - iniconfig=1.1.1
  - intel-openmp=2020.3
  - intervaltree=3.1.0
  - ipykernel=5.3.4
  - ipython=7.22.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isort=4.3.21
  - itsdangerous=1.1.0
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.17.1
  - jinja2=2.11.2
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.1
  - jupyter_server=1.4.1
  - jupyterlab=3.0.14
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.4.0
  - jupyterlab_widgets=1.0.0
  - kealib=1.4.14
  - keyring=22.0.1
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lazy-object-proxy=1.5.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.0.1
  - libcurl=7.80.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libgdal=3.4.0
  - libglib=2.70.2
  - libiconv=1.16
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.8.1
  - libpng=1.6.37
  - libpq=14.1
  - libpysal=4.5.1
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libssh2=1.9.0
  - libtiff=4.3.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - libxslt=1.1.33
  - libzip=1.8.0
  - libzlib=1.2.11
  - locket=0.2.1
  - lxml=4.6.2
  - lz4-c=1.9.3
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - mapclassify=2.4.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.3
  - mccabe=0.6.1
  - mercantile=1.2.1
  - mgwr=2.1.2
  - mistune=0.8.4
  - mkl=2020.4
  - mkl-service=2.3.0
  - mock=4.0.3
  - monotonic=1.5
  - more-itertools=8.12.0
  - mpmath=1.2.1
  - mrio_common_metadata=0.1.1
  - msgpack-python=1.0.2
  - msys2-conda-epoch=20160418
  - munch=2.5.0
  - nbclassic=0.2.6
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - nest-asyncio=1.4.3
  - networkx=2.5
  - nose=1.3.7
  - notebook=6.2.0
  - numexpr=2.7.3
  - numpy=1.19.5
  - numpydoc=1.1.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openpyxl=3.0.6
  - openssl=1.1.1m
  - packaging=20.9
  - pandas=1.3.0
  - pandoc=2.11
  - pandocfilters=1.4.3
  - paramiko=2.7.2
  - parso=0.7.0
  - partd=1.2.0
  - patsy=0.5.1
  - pcre=8.45
  - peewee=3.14.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.1.0
  - pip=21.0
  - pixman=0.40.0
  - plotly=5.5.0
  - pluggy=0.13.1
  - pointpats=2.2.0
  - poppler=21.11.0
  - poppler-data=0.4.11
  - postgresql=14.1
  - presamples=0.2.5
  - proj=8.2.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pulp=2.4
  - py=1.10.0
  - pycodestyle=2.6.0
  - pycparser=2.20
  - pydocstyle=5.1.1
  - pyflakes=2.2.0
  - pygments=2.7.4
  - pylint=2.4.4
  - pynacl=1.4.0
  - pyopenssl=20.0.1
  - pypardiso=0.2.2
  - pyparsing=2.4.7
  - pyprind=2.11.2
  - pyproj=3.3.0
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysal=2.3.0
  - pyshp=2.1.3
  - pyside2=5.13.2
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.2.4
  - pytest-cov=3.0.0
  - python=3.8.6
  - python-dateutil=2.8.0
  - python-jsonrpc-server=0.4.0
  - python-language-server=0.35.1
  - python-levenshtein=0.12.1
  - python_abi=3.8
  - pytz=2020.5
  - pywin32=227
  - pywin32-ctypes=0.2.0
  - pywinpty=0.5.7
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - qdarkstyle=2.8.1
  - qt=5.12.9
  - qtawesome=1.0.1
  - qtconsole=5.0.2
  - qtpy=1.9.0
  - quantecon=0.5.0
  - rasterio=1.2.10
  - rasterstats=0.14.0
  - requests=2.25.1
  - rope=0.18.0
  - rtree=0.9.4
  - salib=1.3.11
  - scipy=1.6.0
  - seaborn=0.11.1
  - seaborn-base=0.11.1
  - segregation=1.3.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - shapely=1.8.0
  - simplejson=3.17.6
  - six=1.15.0
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - snuggs=1.4.7
  - sortedcontainers=2.3.0
  - soupsieve=2.0.1
  - spaghetti=1.6.2
  - spglm=1.0.8
  - sphinx=3.4.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spint=1.0.7
  - splot=1.1.3
  - spreg=1.2.4
  - spvcm=0.3.0
  - spyder=4.1.4
  - spyder-kernels=1.9.4
  - sqlite=3.37.0
  - stats_arrays=0.6.4
  - statsmodels=0.12.1
  - sympy=1.9
  - tbb=2021.4.0
  - tblib=1.7.0
  - tenacity=8.0.1
  - terminado=0.9.2
  - testpath=0.4.4
  - tiledb=2.5.3
  - tk=8.6.10
  - tobler=0.5.4
  - toml=0.10.1
  - toolz=0.11.2
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.0.5
  - typing_extensions=3.10.0.2
  - ucrt=10.0.20348.0
  - ujson=4.0.2
  - unicodecsv=0.14.1
  - unidecode=1.1.2
  - urllib3=1.24.3
  - vc=14.2
  - voluptuous=0.12.1
  - vs2015_runtime=14.29.30037
  - watchdog=1.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - whoosh=2.7.4
  - widgetsnbextension=3.5.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - winpty=0.4.3
  - wrapt=1.12.1
  - xerces-c=3.2.3
  - xlrd=1.2.0
  - xlsxwriter=1.3.7
  - xyzservices=2022.1.0
  - xz=5.2.5
  - yaml=0.2.5
  - yapf=0.30.0
  - zeromq=4.3.3
  - zict=2.0.0
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.5.0
  - pip:
    - deprecated==1.2.13
    - descartes==1.1.0
    - filelock==3.4.2
    - gprof2dot==2021.2.21
    - grpcio==1.43.0
    - joblib==1.0.1
    - kneed==0.7.0
    - llvmlite==0.37.0
    - mizani==0.7.3
    - numba==0.54.0
    - numbakit-ode==0.4
    - palettable==3.3.0
    - pertdist==0.1.1
    - plotnine==0.8.0
    - protobuf==3.19.3
    - pydot==1.4.2
    - python-graphviz==0.18.2
    - ray==1.9.2
    - redis==4.1.1
    - scikit-learn==0.24.2
    - sklearn==0.0
    - snakeviz==2.1.0
    - threadpoolctl==2.1.0

